languageCode = "en-us"
baseurl = "https://rb2nem.github.io/nem-dev-guide/"
theme = "hugo-theme-learn"
description = "Resources for using and developing on NEM"

publishdir = "static"

canonifyURLs = "true"
relativeURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
googleAnalytics = "UA-96593681-1"

[params]
title = "Nem Developer's Guide"
author = "Nem Project"
description = "Resources for using and developing on NEM"
editURL = "https://github.com/rb2nem/nem-dev-guide/edit/master/website/content/"
